### ISSUE TITLE
Próximos passos, tasks, bugs, etc

### ISSUE THREAD

**Issue by dukex** [turicas/brasil.io#1]
Cara tentando achar aqui o que posso ajudar, mas não consegui ver qual direção seguir, tem alguma prioridade? bugs? ou coisa assim?

**Comment by turicas** [comment]
@dukex, obrigado por ter criado as issues! Eu iria criá-las, mas você acabou sendo mais rápido. :-)
Vou fazer o seguinte: responderei as próximas issues, criarei outras aqui **necessárias ao desenvolvimento do software backend da API**. As tarefas e discussões que não tem a ver diretamente com a API serão discutidas na [lista de discussão do projeto](https://groups.google.com/forum/#!forum/brasil-io) (postarei hoje lá mais detalhes sobre o que falta ser feito).

Nota: por essa issue ser apenas uma "dúvida" e ela já ter sido respondida, estou fechando.
