### ISSUE TITLE
Retornar erro 404 se nome da tabela no dataset não existir

### ISSUE THREAD

**Issue by turicas** [turicas/brasil.io#108]
Alguns robôs de buscadores estão fazendo diversas requisições para tabelas que não existem, exemplo:

```
Internal Server Error: /dataset/cursos-prouni/cursoshttps
DoesNotExist at /dataset/cursos-prouni/cursoshttps Table matching query does not exist.
```

```
Internal Server Error: /dataset/cursos-prouni/cursos&amp
DoesNotExist at /dataset/cursos-prouni/cursos&amp Table matching query does not exist.
```

```
Internal Server Error: /dataset/cursos-prouni/cursosA&ccedil
DoesNotExist at /dataset/cursos-prouni/cursosA&ccedil Table matching query does not exist.
```

```
Internal Server Error: /dataset/cursos-prouni/cursosVamos
DoesNotExist at /dataset/cursos-prouni/cursosVamos Table matching query does not exist.
```

Provavelmente eles devem estar parseando de forma incorreta algumas páginas e tentando acessar os links errados (não acredito que esses links estejam desse jeito no próprio Brasil.IO). 

O que acontece é que um erro HTTP 500 é retornado toda vez que tentam acessar, mas um HTTP 404 deveria ser retornado. Precisamos tratar a exceção `Table.DoesNotExist` na chamada de `get_table` na view `dataset_detail`. Por enquanto não precisa ser uma página de erro 404 bonita, pode ser o padrão do Django mesmo (isso faremos na #93).

**Comment by berinhard** [comment]
@turicas como isso não fica espalhado em várias partes do código, não seria jogo resolver isso através de um middleware? Esse middleware poderia capturar todas as exceções de `Dataset.DoesNotExist` ou `Table.DoesNotExist` e levantar um 404. O que acha?

**Comment by turicas** [comment]
@berinhard acho legal usar programação defensiva e, sim, colocar algo em um middleware para mostrar uma página mais amigável, mas nesse caso acho que só um try/except resolve (nesse caso podemos retornar erro 404 com um header `Location` redirecionando para a página-home do dataset ou mostrar um erro mais específico).
