### ISSUE TITLE
Filtrar por registros que possuem valores nulos

### ISSUE THREAD

**Issue by turicas** [turicas/brasil.io#111]
Alguns filtros do tipo "choices" (que aparecem com selects) possuem uma opção "(vazio)" no final, pois alguns desses registros possuem essa coluna com o valor nulo. Mas nunca uma usuária consegue filtrar por esses registros, dado que o valor `None` é passado na querystring. Exemplo: campo `desc_sit_tot_turno` na tabela `candidatos` do dataset `eleicoes-brasil`: https://brasil.io/dataset/eleicoes-brasil/candidatos?desc_sit_tot_turno=None
Não podemos simplesmente passar o valor em branco (https://brasil.io/dataset/eleicoes-brasil/candidatos?desc_sit_tot_turno=), pois quando o valor de um campo na querystring está em branco consideramos que ele não foi passado (como se a pessoa não preenchesse esse campo e clicasse em "filtrar").
Precisamos mudar a lógica do método `apply_filtering` para reconhecer esses casos e filtrar por `<campo>__isnull=True`.

Relacionada a #110.

**Comment by Mdslino** [comment]
É necessário passar o None somente para os campos que são nullable ou não?

**Comment by turicas** [comment]
@Mdslino sim, porém essa verificação é o menor dos problemas: a questão é que hoje não pode-se filtrar pelo valor nulo.

**Comment by billmask** [comment]
Turicas, 3 possíveis caminhos me veem a mente agora:

1) Update nos nulos para valores irreais (idade negativa, nome xxxxxxxxxxxxxxxxxxxx, data absurda)

2)  Aplicar sua solução que seria usar coluna IS NULL
"Precisamos mudar a lógica do método apply_filtering para reconhecer esses casos e filtrar por <campo>__isnull=True."

3) Verifiacr o lenght da coluna e ver se é 0, mas isso seria problemático para indexar.

Onde está essa parte do dado que sou chucro nesse negócio aqui de Coding+GitHub

**Comment by turicas** [comment]
> 2. Aplicar sua solução que seria usar coluna IS NULL
>    "Precisamos mudar a lógica do método apply_filtering para reconhecer esses casos e filtrar por __isnull=True."

Essa é a melhor solução. Se o valor que chegar for `None`, fazemos a checagem por `__isnull=True`.

Issue relacionada com #189.
