### ISSUE TITLE
Mostrar data da captura e data de importação

### ISSUE THREAD

**Issue by turicas** [turicas/brasil.io#112]
Atualmente mostramos "Última atualização: <data>", mas isso não está dizendo exatamete o que aquela informação quer dizer. No model `Table` temos o campo `last_update`, que na verdade é a data em que os dados daquela tabela foram importados. Porém essa data não é a mesma data em que os dados foram capturados (a data de captura está dentro de `Version`). Então, precisamos:

- [ ] Alterar o nome do campo `last_update` para `import_date`
- [ ] Mostrar no frontend a data de captura (essa sempre teremos preenchida na `Version` daquela `Table`)
- [ ] Caso `import_date` da `Table` esteja preenchida, mostramos também essa informação
- [ ] Adicionar essas informações na API também

No final, vai ficar assim:
- Se `import_date` estiver preenchido: "Dados capturados em <version.collected_at>. Importação dos dados feitas em <table.import_date>."
- Se `import_date` não estiver preenchido: "Dados capturados em <version.collected_at>."

**Comment by lucashanke** [comment]
Posso ajudar nessa issue, @turicas . Se quiser fazer o assigment. ;)
