### ISSUE TITLE
Dados soltos

### ISSUE THREAD

**Issue by irioborges** [turicas/brasil.io#126]
Oi pessoal, eu tava dando uma olhada, mas vejo muitos dados soltos e pouca informação, gostaria de saber como posso contribuir para chegar a conclusões em cima destes dados. Muito legal a iniciativa! Abraços!

**Comment by turicas** [comment]
Oi, Írio, tudo bem? Não entendi o que você quis dizer com "dados soltos": diversos datasets possuem links para outros datasets e é possível você fazer buscas e filtros nos dados (que já estão limpos e organizados em um só lugar, diferente de como estão nas fontes originais).
Para mais detalhes sobre como colaborar com o projeto, [leia essa página](https://brasil.io/colabore).
