### ISSUE TITLE
Códigos IBGE

### ISSUE THREAD

**Issue by alexandre-mbm** [turicas/brasil.io#13]
Provavelmente você os obteve usando o [rows](/turicas/rows). Então acho muito pouco provável que isto tenha alguma utilidade para você, mas se quiser pode aproveitar: [IBGETools/data/ibge_query.py](https://github.com/alexandre-mbm/IBGETools/blob/9546092f0d6fe4ec5d8121e8c105e5ccca91eb88/data/ibge_query.py). **Parabéns pelo rows!**

**Comment by turicas** [comment]
Obrigado pelo link, @alexandre-mbm! :-)
Adicionei o site da RAIS na [issue referente a fontes de informação](https://github.com/turicas/www.brasil.io/issues/2).

Com relação aos dados do IBGE, ainda vou criar um repositório com o código que fiz para capturar os dados (que usa a lib [rows](https://github.com/turicas/rows)).

Como nesse repositório o foco é o desenvolvimento do backend da API (e não na coleta dos dados em si), vou fechar essa issue.
