### ISSUE TITLE
Erro quando roda python manage.py update_data

### ISSUE THREAD

**Issue by juhhcarmona** [turicas/brasil.io#137]
Quando roda o comando ele gera esse erro: 

![captura de tela 2018-08-22 as 18 15 31](https://user-images.githubusercontent.com/1108268/44524222-064f0980-a6b3-11e8-90dc-5db48e0b564a.png)

**Comment by turicas** [comment]
Obrigado por reportar! :)
O erro aconteceu pois estamos começando a preencher os campos `description` de `Field` para termos mais metadados dos datasets e uma das descrições é maior que 255 caracteres. Resolvi isso no commit 6bb3c092e3caf44a7635cd4191c61b896c616d65. Para corrigir, basta:

- Atualizar seu repositório (algo como: `git checkout develop && git pull turicas develop`)
- Rodar a migração: `python manage.py migrate`
- Atualizar os dados: `python manage.py update_data --truncate`
