### ISSUE TITLE
Dados de interesse político

### ISSUE THREAD

**Issue by alexandre-mbm** [turicas/brasil.io#14]
Proponho uma [conversa](/olhoneles/olhoneles/issues/20) entre o [olhoneles](/olhoneles/olhoneles) e o [api.brasil.io](/turicas/api.brasil.io). Eu posso trabalhar dados potiguares de interesse político. Vocês só tem de acordar uma estruturação de dados útil e satisfatória para os dois projetos.

**Comment by turicas** [comment]
@alexandre-mbm, estou em contato com o @gnoronha e, tão logo a API esteja disponível para entrada de dados, faremos uma integração entre os projetos.

Nota: como aqui é o repositório de desenvolvimento do backend da API, esse tipo de discussão não se encaixa bem -- o ideal seria [a lista de discussão do Brasil.IO](https://groups.google.com/group/brasil-io).

**Comment by alexandre-mbm** [comment]
Lá no site deles, após eles falarem que interagiram com você, comecei a pensar o que fazer. Tenho documento na própria [issue](olhoneles/olhoneles/issues/20), por enquanto. Mas hoje isso está "pausado"; em parte, porque eu pedi a eles uma validação do que eu penso ter entendido e eles ainda não responderam. Mas não é só isso; também tenho me ocupado com outras coisas.
