### ISSUE TITLE
Baixar dados completos do TSE

### ISSUE THREAD

**Issue by AliferSales** [turicas/brasil.io#146]
Nas tabelas do conjunto de dados do TSE, em

> *Você também pode baixar o dataset completo ou utilizar nossa API.*

o redirecionamento para baixar o dataset completo não está funcionando. O link leva somente para a raiz do google drive, não permitindo o dowload completo dos dados.

Ao realizar alguns filtro, entretanto, o botão de BAIXAR RESULTADOS EM CSV aparece (aparentemente quando o volume de dados está abaixo de um upper bound.)

Imagino que, como o volume de dados do TSE é muito grande, colocá-los no Google Drive pode gerar custos. Mas, de qualquer forma, a situação pode gerar uma sensação de bug para alguns usuários.

**Comment by paulohrpinheiro** [comment]
Eu não testei todos, mas eu tentei com dados de sócios e lista de cpf/cnpf, tive o mesmo problema. Alguma coisa em que eu possa ajudar no projeto?

**Comment by turicas** [comment]
Oi, pessoal, esclarecendo:

- Quando você faz algum filtro e clica em "baixar resultado em CSV" o arquivo é gerado sob demanda, pegando os dados diretamente do banco de dados (esse botão só aparece se o resultado dos filtros for menor que 350.000 registros - esse limite existe por causa do tamanho/tempo de geração, se você quiser algum resultado maior que isso provavelmente vai querer baixar o dataset inteiro);
- Nem todos os datasets completos estão disponíveis para download por conta de algumas questões:
  - Alguns possuem dados sensíveis (como o documentos-brasil, que possui os CPFs de milhões de brasileiros) e ainda preciso criar uma rotina para gerar os CSVs com os dados obfuscados;
  - Ainda não temos uma maneira fácil e barata de armazenar os dados e como o projeto tem recursos limitados, evitei subir todos os arquivos que tenho.

Nosso objetivo é que qualquer um possa rodar os scripts que geram os dados limpos; caso queiram os dados completos e por um dos motivos acima eles não estejam disponíveis, sugiro ir até o repositório dos scripts e rodá-los. Nosso objetivo é ter todos os arquivos disponíveis para download em breve, mas ainda precisamos ajustar como a plataforma irá servir os arquivos estáticos (os grandes, com dados, não CSS/JS/imagens do sistema) e configurar a execução automática dos scripts.
