### ISSUE TITLE
Implementar busca em datasets

### ISSUE THREAD

**Issue by turicas** [turicas/brasil.io#148]
Buscar pelo nome e descrição.
Sugerida pela @juhhcarmona.
Tem a ver com #128.

**Comment by masreis** [comment]
O que acham de implantar com um Lucene/Solr/Elasticsearch?
Eu me candidataria.

**Comment by turicas** [comment]
@masreis essa busca foi implementada e é bem simples (somente no nome/descrição), mas temos vontade de usar o elasticsearch para melhorar a busca nos *dados* dos datasets, porém é algo que precisamos planejar mais. Se tiver disponibilidade, que tal conversamos lá no [chat.brasil.io](https://chat.brasil.io)?
