### ISSUE TITLE
Corrigir página de contribuidores

### ISSUE THREAD

**Issue by turicas** [turicas/brasil.io#166]
```
Internal Server Error: /contribuidores
timeout at /contribuidores The read operation timed out
```

Tarefas:

- [x] Criar cache de requisições de contribuidores do GitHub (talvez num arquivo no repositório ou em um servidor de cache)
- [x] Adicionar lista de outros repositórios (dos scripts, além da plataforma)
- [x] Ver se é possível adicionar contribuidores do GitHub que comentaram/criaram issues (além dos que contribuíram com código)

**Comment by turicas** [comment]
No commit 355559b6011c04c04d57a58db01a81186db8cd91, melhorei a forma de pegar o JSON com os contribuidores (agora tem um cache que funciona sempre) e esclareci que nessa página estão listados apenas contribuidores de código, com links para outros contribuidores (financeiros e voluntários).

**Comment by lucianosousa** [comment]
A lista de contribuidores do github tem como pegar na API deles.
Fiz uma pesquisa e existe uma lib em python que possui essa query
https://pygithub.readthedocs.io/en/latest/github_objects/Repository.html?highlight=stats#github.Repository.Repository.get_contributors

**Comment by turicas** [comment]
> A lista de contribuidores do github tem como pegar na API deles.
> Fiz uma pesquisa e existe uma lib em python que possui essa query
> https://pygithub.readthedocs.io/en/latest/github_objects/Repository.html?highlight=stats#github.Repository.Repository.get_contributors

O código que fiz está pegando da API, só não usa a biblioteca porque são chamadas simples que eu preferi implementar na mão (usando urllib) pra ter menos dependências.

**Comment by turicas** [comment]
Como a página de contribuidores foi resolvida, vou fechar essa issue, dado que separei a parte de doadores na #291
