### ISSUE TITLE
Declarar HTTP Strict Transport Security

### ISSUE THREAD

**Issue by turicas** [turicas/brasil.io#17]
https://tools.ietf.org/html/rfc6797

**Comment by flavioamieiro** [comment]
A app Flask tá rodando direto como servidor HTTP ou tem um nginx na frente?

Se tiver um nginx, eu recomendo usar as configurações que tão em [ioerror/duraconf](https://github.com/ioerror/duraconf/blob/master/configs/nginx/nginx.conf). Esse repositório é bem bom, inclusive.

**Comment by turicas** [comment]
Tem um nginx na frente (lembra do 502 que apareceu para você?) -- ainda preciso atualizar o fabfile com as configurações do nginx.

**Comment by flavioamieiro** [comment]
Verdade, tinha esquecido :grin: 

Pra declarar o htst o que você precisa é só [adicionar o header Strict-Transport-Security](https://github.com/ioerror/duraconf/blob/master/configs/nginx/nginx.conf#L82), mas não esquece de [redirecionar da porta 80 pra 443 sempre](https://github.com/ioerror/duraconf/blob/master/configs/nginx/nginx.conf#L49-L52).
