### ISSUE TITLE
Links quebrados em dataset/documentos-brasil

### ISSUE THREAD

**Issue by adorilson** [turicas/brasil.io#172]
A pagina https://brasil.io/dataset/documentos-brasil possui links para https://github.com/turicas/documentos-brasil e https://brasil.io/dataset/eleicoes, mas eles estão quebrados.

**Comment by billmask** [comment]
O link de eleições acredito que seja: https://brasil.io/dataset/eleicoes-brasil/candidatos
O repositório sumiu ou o Turicas deixou privado. Não encontrei o repo do site para fazer PR :_(.

**Comment by turicas** [comment]
Como esse dataset possui dados sensíveis (CPFs com os nomes completos) e estamos reestruturando a forma como consolidaremos os dados de entidades (pessoas, empresas etc.) na plataforma, não vamos disponibilizar os dados desse dataset por enquanto. Ele existe somente para facilitar que a plataforma consiga fazer os relacionamentos internos no banco e dados e nem deveria ficar visível (coloquei só porque pode facilitar para alguém).

**Comment by turicas** [comment]
Por enquanto deixei esse dataset como invisível (ele não aparecerá na home, nem na lista de datasets, mas quem acessar diretamente a URL dele conseguirá ver os dados). Isso ficará assim até resolvermos #182, por isso fecharei essa issue.
