### ISSUE TITLE
Criar script para gerar página de arquivo estático de datasets

### ISSUE THREAD

**Issue by turicas** [turicas/brasil.io#183]
Ainda não temos uma página que lista os arquivos estáticos de dataset pra download (por enquanto o link vai para o Google Drive, mas vamos movê-los para nossa nova hospedagem de arquivos estáticos: https://data.brasil.io/).
É necessário modificar o script `mirror/generate_list.py` para que ele seja capaz de gerar essa página também. Além disso, um novo template precisará ser criado em `mirror/templates`.

**Comment by turicas** [comment]
Script modificado.
Precisamos integrar:
- Coleta de dados
- `import_data`
- Geração dessa página

**Comment by fbobraga** [comment]
Quem custeia esse data.brasil.io? Doações?

**Comment by turicas** [comment]
@fbobraga inicialmente, eu. Depois, as doações em [nossa campanha de financiamento coletivo](https://apoia.se/brasilio). Lembrando que os custos de hospedar os dados para download são apenas parte dos custos totais (tem os servidores com a aplicação Web, API e banco de dados, serviços contratados para manter tudo online, horas de trabalho etc.).

**Comment by turicas** [comment]
Essa issue é antiga, já foi parcialmente implementada em outras e o que falta dela já está descrita em outras mais específicas (como a #414). Por isso, vou fechá-la.

**Comment by fbobraga** [comment]
Pode citar algumas dessa outras issues? Me ajudaria muito

Em sex, 9 de out de 2020 12:38, Álvaro Justen <notifications@github.com>
escreveu:

**Comment by fbobraga** [comment]
Ops, nem agora que vi a ref pra #414 (tô vendo ela, desculpe)

**Comment by fbobraga** [comment]
Pode citar mais algumas? (A #414 já tá fechada e diz muito pouco)

**Comment by fbobraga** [comment]
Como as contribuições do https://apoia.se/brasilio são usados? Como é a transparência disso?
