### ISSUE TITLE
Passar schema para pgimport no import_data

### ISSUE THREAD

**Issue by turicas** [turicas/brasil.io#184]
Se não passarmos, a função vai tentar detectar o schema do CSV e pode ser que detecte diferente do que foi definido no model `Field` - dependendo das diferenças isso poderá ocasionar erro no COPY.
Precisamos conseguir gerar um objeto `OrderedDict` a partir da `Table` - poderia existir um método no model para isso.

**Comment by berinhard** [comment]
@turicas se entendi bem, teríamos que implementar um método no model de `Table`, algo como `table.get_schema()` que retornasse um `dict` como é esperado pelo rows no [parâmetro `schema`](https://github.com/turicas/rows/blob/develop/rows/utils.py#L918), certo?

**Comment by turicas** [comment]
> @turicas se entendi bem, teríamos que implementar um método no model de `Table`, algo como `table.get_schema()` que retornasse um `dict` como é esperado pelo rows no [parâmetro `schema`](https://github.com/turicas/rows/blob/develop/rows/utils.py#L918), certo?

Na verdade um `collections.OrderedDict`. Veja a função `rows.utils.load_schema`, pode ajudar.
