### ISSUE TITLE
Limitar tempo de consultas de usuários

### ISSUE THREAD

**Issue by turicas** [turicas/brasil.io#206]
Algumas consultas de busca feitas por usuários estão ocupando os workers do PostgreSQL e tornando todo o site mais lento (enfileirando), exemplo:

```sql
SELECT "data_documentosbrasil_documents"."id", "data_documentosbrasil_documents"."document_type", "data_documentosbrasil_documents"."document", "data_documentosbrasil_documents"."name", "data_documentosbrasil_documents"."sources", "data_documentosbrasil_documents"."text", "data_documentosbrasil_documents"."docroot", "data_documentosbrasil_documents"."search_data" FROM "data_documentosbrasil_documents" WHERE "data_documentosbrasil_documents"."search_data" @@ (plainto_tsquery('pg_catalog.portuguese'::regconfig, 'artflex')) = true ORDER BY "data_documentosbrasil_documents"."name" ASC  LIMIT 20
```

Temos que matar essas consultas caso ultrapassem um limite (20s), mas não podemos fazer isso com todas as consultas, pois muitos datasets ao serem importados no `import_data` demoram um tempo razoável executando o comando `COPY`. A alternativa talvez seja criar um usuário diferente para o `import_data`, com o `statement_timeout` ilimitado e limitar o usuário da aplicação Django que faz as buscas:

`ALTER ROLE <user> SET statement_timeout TO '10s';`

Pode ser resolvido com a sugestão de adicionar o SET TIMEOUT no wsgi: https://medium.com/@hakibenita/9-django-tips-for-working-with-databases-beba787ed7d3

**Comment by fabriziomello** [comment]
@turicas baseado no seu relato essa é a melhor solução a curto prazo. A médio e longo importante analisar as queries que estão demorando mais de 20s para avaliar oportunidades de refatoração
