### ISSUE TITLE
Comunidades

### ISSUE THREAD

**Issue by elyfran** [turicas/brasil.io#21]
Boa tarde,

Seria possível ter a lista das comunidades de um município?

**Comment by turicas** [comment]
@elyfran, a ideia do brasil.io é só direcionar e/ou hospedar os dados e não ser fonte original deles.
Você conhece alguma instituição que tenha coletado esses dados para que possamos disponibilizar?

**Comment by elyfran** [comment]
@turicas 
Bom dia, tudo bem? Infelizmente até o momento não tenho conhecimento de tal disponibilidade de serviço que possa fornecer essas informações, mas se conseguir certamente entrarei em contato.

Mas obrigado pelo apoio e atenção.
