### ISSUE TITLE
COVID19 - É possível o dataset trabalhar com casos suspeitos também?

### ISSUE THREAD

**Issue by leandrogm** [turicas/brasil.io#219]
Bom dia,
Antes de tudo obrigado pela contribuição desse projeto à comunidade e à sociedade brasileira :D.
Estou atualmente trabalhando em uma equipe que está desenvolvendo uma ferramenta para facilitar a gestão do covid19 junto às prefeituras. Hoje estamos trabalhando próximos da prefeitura de Bauru mas, quando sairmos do beta, queremos disponibilizar essa ferramenta para outras prefeituras do país em breve. 
O que pude perceber até agora é que as prefeituras, que eu pesquisei, consideram bem relevantes a questão dos casos `suspeitos`, pois como o exame para a confirmação está demorando bastante, eles estão definindo algumas políticas com base nesse indicador.
Eu dei uma olhada no dataset disponível [aqui](https://brasil.io/dataset/covid19/caso) e apesar de estar bem completo não tem essa informação.
Na verdade eu não sei nem se estou fazendo essa pergunta no lugar certo e também não entendo as implicações de pegar essa outra informação de maneira global para todas as prefeituras do país, mas eu gostaria de saber se é possível e se posso ajudar de alguma maneira.

**Comment by turicas** [comment]
Por enquanto não vamos coletar essa informação, pois:
1- Não são todas as Secretarias Estaduais de Saúde (SES) que divulgam essa informação
2- O processo é manual e qualquer adição faria com que houvesse uma demora na atualização de nossos dados.
O que você pode fazer para ajudar:
- Cobrar às SES que não divulgam esse dado que passem a divulgar
- Cobrar às SES que divulguem os dados de maneira estruturada para que possamos coletar automaticamente ([veja o texto que fiz com recomendações](https://github.com/turicas/covid19-br/blob/master/recomendacoes.md))
