### ISSUE TITLE
Dados ambientais sobre municípios 

### ISSUE THREAD

**Issue by samuelyeshua** [turicas/brasil.io#22]
A ideia é exatamente o que eu procurava, porém eu precisava de dados mais detalhados sobre os municípios em si, principalmente sobre meio ambiente...

Fica a sugestão para futuras implementações

**Comment by turicas** [comment]
@samuelyeshua, você tem ideia de fontes em que esses dados poderiam ser baixados, para serem convertidos e liberados no Brasil.IO?

**Comment by turicas** [comment]
@samuelyeshua, caso tenha sugestões mais concretas, por favor preencha o formulário [Sugira um dataset](https://brasil.io/datasets/sugira).
