### ISSUE TITLE
Horário atualizações

### ISSUE THREAD

**Issue by smolski** [turicas/brasil.io#220]
Olá, parabéns pelo projeto!

Gostaria de saber qual é o horário de atualização das informações? Pergunto pois atualizo diariamente e nem sempre estão todos os dados dos Estados e municípios ao mesmo tempo.

**Comment by turicas** [comment]
O processo é:

- Secretaria Estadual lança algum boletim
- Algum dos voluntários responsáveis pelo estado coleta os dados
- Outro voluntário checa os dados
- Nosso software que fazer outras checagens automáticas executa e então atualiza os dados

Dependendo do horário em que as SES disponibilizam os boletins, os dados podem ser atualizados várias vezes por dia. Hoje especialmente foi um dia atípico, pois estamos fazendo algumas checagens extras. Acabamos de atualizar.
