### ISSUE TITLE
Mudança do footer na versão mobile

### ISSUE THREAD

**Issue by LucasAmaral42** [turicas/brasil.io#221]
Sugestão: Está sobrepondo o conteúdo da página e pode ter uma melhoria na visualização do conteúdo do footer para o usuário mobile.

![image](https://user-images.githubusercontent.com/42688542/79180862-62632600-7de1-11ea-8702-6d97e07536cf.png)

**Comment by turicas** [comment]
Oi, @LucasAmaral42. Eu já tinha percebido o problema, mas ainda não consegui parar para arrumar (muita demanda ultimamente). Você poderia criar um pull request com a alteração que corrige o problema?

**Comment by LucasAmaral42** [comment]
Consigo, vou preparar o ambiente para ajudá-los
