### ISSUE TITLE
Inlcuir link para a visualização dos dados da Covid-19

### ISSUE THREAD

**Issue by augusto-herrmann** [turicas/brasil.io#233]
Incluir, na página do [dataset da Covid-19](https://brasil.io/dataset/covid19/caso/), um link para a [visualização](https://brasil.io/covid19/) [lançada neste fim de semana](https://blog.brasil.io/2020/04/18/painel-covid19-e-2-anos-de-brasilio/) pelo @turicas.

Procurei o template daquela página, que já inclui diversos links relevantes relacionados ao dataset da Covid-19, mas não o encontrei, senão já teria feito o PR que suponho que seja algo simples de se fazer.

**Comment by turicas** [comment]
Coloquei a frase "Acesse também o [**Painel COVID-19**](https://brasil.io/covid19/)." na descrição das tabelas do dataset (diretamente pela interface administrativa do banco de dados).
