### ISSUE TITLE
Validar email no form de contato

### ISSUE THREAD

**Issue by turicas** [turicas/brasil.io#243]
Além disso, aproveitar para mudar o título do email (eu recebo e fica tudo na mesma thread, o ideal é ter algo que identifique aquele email, como nome da pessoa e/ou data e hora)

**Comment by berinhard** [comment]
@turicas pelos testes que fiz aqui a validação do email já está rolando sim. O campo do form [já é um  `EmailField`](https://github.com/turicas/brasil.io/blob/develop/core/forms.py#L100) e como o form tá renderizado via [`form.as_p`](https://github.com/turicas/brasil.io/blob/develop/core/templates/contact.html#L27) ele já está, inclusive, com a validação do browser para `input type="email"`.

De qualquer forma, mudei o assunto pra adicionar o nome da pessoa.
