### ISSUE TITLE
Melhorar admin para Covid19

### ISSUE THREAD

**Issue by berinhard** [turicas/brasil.io#246]
- [x] Na listagem das planilhas mudar cancelled pra active e inverter o valor (active = not cancelled) 
- [x] Na listagem de usuários, poder filtrar pelos grupos de permissão por estado

**Comment by turicas** [comment]
Primeiro item resolvido em ad46f3d5a4e6eacd311404232352a25976136ec1

**Comment by berinhard** [comment]
Fechando essa tarefa porque a parte complementar foi resolvida em #253
