### ISSUE TITLE
Painel COVID Registral. Óbitos por doenças respiratórias do registrocivil.org

### ISSUE THREAD

**Issue by avila** [turicas/brasil.io#255]
Há planos de incluir as informações adicionais do [Painel COVID Registral](https://transparencia.registrocivil.org.br/registral-covid) do portal da transparência do registro civil?  

Neste painel eles incluiram: 
-    Síndrome respiratória aguda grave (SRAG)
-    Pneumonia
-    Insuficiência respiratória
-    Septicemia (sepse/choque séptico)
-    Indeterminadas (causas mortes ligadas a doenças respiratórias, mas não conclusivas)
-    Demais óbitos (todos os outros tipos de óbitos que não estão listados a cima)

Com esses dados deve ser possivel calcular, de forma mais precisa, o excesso de mortes.

**Comment by turicas** [comment]
@avila, sim, temos planos =) 
Vou fechar essa issue porque criei uma no repositório correto, ok? https://github.com/turicas/covid19-br/issues/114

**Comment by endersonmaia** [comment]
@turicas só pra informar

dependendo das permissões do repositório, é possível transferir as issues 

![Captura de Tela 2020-04-30 às 21 38 16](https://user-images.githubusercontent.com/370/80771812-f85db700-8b2a-11ea-968d-b0dd3c122a0d.png)
