### ISSUE TITLE
Tornar integração com Google Spreadsheet mais resiliente

### ISSUE THREAD

**Issue by berinhard** [turicas/brasil.io#271]
A `rows` tem levantado 2 exceções nas integrações com o Google Spreadsheet nas funções do módullo `covid19/google_data.py`, sendo elas a `StopIteration` e a `BadZipFile`. Maneiras de contornar esse problema seriam:

- [ ] Adicionar a resposta da planilha geral com dados das pessoas colaboradoras ao cache no Redis;
- [ ] Implementar um processo de retry no caso de erro de importação com o rows nas chamadas do Google Spreadsheet.

**Comment by turicas** [comment]
Acho que vale fazer ambos, dado que o erro pode ser na transferência dos dados (acho difícil, mas já vi o Google Spreadsheets não enviar o arquivo completo).
