### ISSUE TITLE
UX Design nos projetos

### ISSUE THREAD

**Issue by cadeskriacao** [turicas/brasil.io#278]
Fala pessoal, tranquilo?

Gostaria de saber se é do interesse de vocês integrar um UX Designer na equipe, estou diminuindo os meus jobs remunerados pra dar apoio a quem precisa.

Qualquer coisa estou na área, tamo junto!
Abração!

**Comment by berinhard** [comment]
olá @cadeskriacao! tudo certo e contigo?

valeu pela disponibilidade! você já entrou no [Chat do Brasil.io](https://chat.brasil.io/)? tem uma frente que estou tocando com o @turicas que seria ótimo ter alguém que saque mais de frontend pra ajudar.

abraços

**Comment by berinhard** [comment]
quando entra por lá, me manda uma mensagem. meu @ é @berin.
