### ISSUE TITLE
Automatizar geração de listagem de arquivos para download

### ISSUE THREAD

**Issue by turicas** [turicas/brasil.io#284]
Atualmente a página de listagem presente em https://data.brasil.io/dataset/X/_meta/list.html está sendo gerada manualmente ou pelos scripts do próprio dataset. O ideal é que o backend do Brasil.IO gere/hospede essa página. Para isso, o backend precisará saber quais arquivos precisam ser hospedados e o sha512 de cada um deles.

Nota: não apenas os arquivos de datasets são mostrados nessas páginas. Temos também os mirrors.

**Comment by berinhard** [comment]
Essa issue foi mais bem elaborada depois na issue #357 e resolvida pelo PR #386
