### ISSUE TITLE
Deve ser possível usuário invalidar planilha já enviada

### ISSUE THREAD

**Issue by endersonmaia** [turicas/brasil.io#288]
Por acidente, enviei a planilha pro dia errado, e gostaria de ir no registros daquele envio, e invalidá-lo.

Isso evita que alguém envie uma planilha correta e sejam emitidas verificações em cima de dados inválidos.

/label covid-19

**Comment by augusto-herrmann** [comment]
Posicionamento do @turicas sobre isso (copiado do Rocket Chat):

>  se vcs esperarem sair o boletim de hoje com os dados corretos, o sistema vai sobrescrever
> 
> mas como vcs dois enviaram a planilha de hoje, ela já está como "deployed" e assim que eu rodar o deploy depois disso, vamos ter os dados de hj tb no sistema
> 
> dar a opção de vcs deletarem/cancelarem planilhas pode ser algo perigoso em alguns casos (por conta de perder historico e de como os dados estao no sistema). como isso tb custará horas de desenvolvimento, acho que o melhor agora é eu entrar manualmente no banco de dados e deletar

Acho que faz sentido. Mais seguro é mesmo enviar outra e sobrescrever os dados.

**Comment by berinhard** [comment]
Concordo demais com a mensagem do @turicas no Rocket Chat. Podemos fechar essa issue então?

**Comment by endersonmaia** [comment]
> Concordo demais com a mensagem do @turicas no Rocket Chat. Podemos fechar essa issue então?

Sim, inclusive eu já recorri a este procedimento de sobrescrever a planilha.
