### ISSUE TITLE
Melhorias no Front-end

### ISSUE THREAD

**Issue by thulioph-tw** [turicas/brasil.io#289]
Dei uma revisada no código pra entender a estrutura e queria propor alguns pontos de melhoria. Acredito que eles podem ser as mudanças iniciais, pela baixa complexidade na execução e pela entrega de valor tanto pra quem tá usando como pra quem tá contribuindo.

Utilizei o [Lighthouse](https://developers.google.com/web/tools/lighthouse) pra coletar algumas métricas e deixo o link contendo o resultado do relatório gerado.

- [Home](https://gist.github.com/thulioph-tw/e9b01c8acb00b501c2d56561e75c7e14#file-home-json)
- [Covid19](https://gist.github.com/thulioph-tw/e9b01c8acb00b501c2d56561e75c7e14#file-covid19-json)

### Carregamento

O carregamento das páginas, está sendo impactado por conta da ordem de *imports* de alguns assets (**fonts**, **bibliotecas** e **imagens**). Assim como a não utilização de versões *minificadas* e *gzipadas* de bibliotecas e também código que **não está sendo utilizado**. O ideal para este cenário seria a utilização de uma ferramenta de bundle para auxiliar na automação do processo.

### Acessibilidade e SEO

Algumas pequenas mudanças podem ajudar outras pessoas a utilizarem e descobrirem este conteúdo. Utilização do atributo `alt` em algumas imagens, `name` para alguns links e adição de algumas *meta-tags* nos cabeçalhos. As mudanças aqui não precisam de automação, são bem pontuais e as próximas adições precisam apenas seguir o modelo existente.

### Segurança

Uma das bibliotecas utilizadas possui uma vulnerabilidade reportada que seria importante atualizar. Para uma melhor cobertura, o ideal seria adicionar um passo de verificação de vulnerabilidades na hora do build e algo como o [npm audit](https://docs.npmjs.com/auditing-package-dependencies-for-security-vulnerabilities).

Vi que parte dos pontos comentados já estão sendo resolvidos em outras issues, posso criar mais issues a partir desta. O que acham?

**Comment by thulioph** [comment]
## Issues

Listando aqui todas as issues relacionadas a **Front-end** pra que a gente consiga mapear e saber como tá o andamento de cada uma.

- [#249 - Servir todos os assets em vez de usar sites externos](https://github.com/turicas/brasil.io/issues/249)

- [#265 - Melhorar apresentação do Dashboard Covid-19 no mobile](https://github.com/turicas/brasil.io/issues/265)

- [#297 - Atualizar a ordem dos imports para evitar bloqueio do carregamento da página](https://github.com/turicas/brasil.io/issues/297)

- [#292 - Adicionar meta-tags específicas de SEO](https://github.com/turicas/brasil.io/issues/292)

- [#296 - Adicionar em todas as imagens o atributo `alt` e `name` para os links](https://github.com/turicas/brasil.io/issues/296)

- [#293 - Adicionar suporte para `npm audit`](https://github.com/turicas/brasil.io/issues/293)

- [#294 - Adicionar o Webpack para automação na otimização dos assets (concatenar, minificar, remover código não utilizado, otimizar imagens, etc)](https://github.com/turicas/brasil.io/issues/294)

- [#295 - Adicionar git hooks para automação na verificação de lint e audit](https://github.com/turicas/brasil.io/issues/295)

**Comment by turicas** [comment]
Muito obrigado, @thulioph! Como as outras issues foram criadas, acha que podemos fechar essa daqui? Daí discutimos em detalhes nas outras.

**Comment by thulioph** [comment]
Podemos sim!
