### ISSUE TITLE
Como criar novos recursos/coleção de recursos? Qual deve ser a URL dele?

### ISSUE THREAD

**Issue by dukex** [turicas/brasil.io#3]

**Comment by dukex** [comment]
eu acho que dever ser sempre o nome no plural, para seguir o padrão REST

**Comment by turicas** [comment]
Tentando fazer essa pergunta de forma mais clara e aplicada aplicada: dado que existe o recurso `/unidades-federativas/rj/municipios/tres-rios/camara`, representando a câmara de vereadores do município de Três Rios/RJ, como um usuário poderia criar uma coleção chamada `vereadores` dentro desse recurso e então adicionar recursos dentro dessa coleção? Mais detalhadamente:
- Qual _schema_ ele usaria para a requisição `PUT /unidades-federativas/rj/municipios/tres-rios/camara/vereadores`?
- O que iria no corpo da requisição?

**Comment by turicas** [comment]
@rodsenra comentou comigo por e-mail que ele tem usado sempre o padrão `/namespace/Classe/instâncias` para as URLs.
Nesse caso, como existe um hierarquia clara entre os recursos, não vejo problemas em aninhar (`/classe1/instancia1/classe2/instancia2`).
