### ISSUE TITLE
API deveria retornar dados totalizados para o Brasil

### ISSUE THREAD

**Issue by ncesar** [turicas/brasil.io#305]
ref: https://github.com/turicas/covid19-br/issues/165
Gostaria de saber se é possível receber um json dessa maneira(e com apenas o Brasil de objeto, sem outros extras): 
```json
    {
      "country": "Brazil",
      "city_ibge_code": "null",
      "confirmed": 30000,
      "confirmed_per_100k_inhabitants": 4.98355,
      "date": "2020-03-26",
      "death_rate": null,
      "deaths": 30000,
      "estimated_population_2019": 2000066,
      "is_last": true,
      "place_type": "country"
    },
```

Por exemplo: `https://brasil.io/api/dataset/covid19/caso/data?country=Brasil`

**Comment by turicas** [comment]
A API é gerada automaticamente a partir dos datasets. Para retornar isso, precisaríamos retornar mais uma tabela com os dados totalizados e isso vai atrapalhar o processo de atualização (já estamos bastate sobrecarregados).
Sugiro filtrar por `place_type=state&is_last=True` para ter os últimos dados por estado, daí basta somar os 27 registros.
