### ISSUE TITLE
Sistema ignora planilhas de COVID-19 enviadas

### ISSUE THREAD

**Issue by endersonmaia** [turicas/brasil.io#306]
Ao enviar uma planilha em https://brasil.io/admin/covid19/statespreadsheet/add/, o sistema processa mas parece não acatar a planilha.

Percebi isso ao enviar minha planilha, e após o pjveras enviar a dele, o sistema não informou que já haviam duas planilhas enviadas.

Isso aconteceu com outras pessoas também, como foi reportado no canal #covid19 no chat.brasil.io

**Comment by endersonmaia** [comment]
foi nesta thread que comentamos o problema

https://chat.brasil.io/group/covid19?msg=igk86PYwZhB8D9kMC

**Comment by turicas** [comment]
Corrigido.
