### ISSUE TITLE
Data de captura dos dados incorreta

### ISSUE THREAD

**Issue by marcelogui** [turicas/brasil.io#325]
![image](https://user-images.githubusercontent.com/16950868/83958597-fd103c00-a849-11ea-89cf-42296b5f23c2.png)

A data de captura informa que ela foi realizada amanhã. Não sei se isso foi um problema apenas agora ou se é um problema automático. Busquei nos dados mas todos tem a última data correta 2020-06-06

**Comment by turicas** [comment]
@danielfsbarreto obrigado! Acabei de transferir a issue. Acho que no backend o fuso horário está correto, mas o erro acontece na hora de importar os dados - vou checar.

**Comment by turicas** [comment]
Fiz uma alteração no script que atualiza os dados para usar o timezone UTC-3 e acredito que agora vá funcionar (fiz alguns testes, mas preciso esperar até às 21h de hoje para fazer um deployment dos dados e ver a data que fica). Vou fechar essa issue por enquanto.
