### ISSUE TITLE
Deploy de uma instância própria do Sentry

### ISSUE THREAD

**Issue by turicas** [turicas/brasil.io#331]
Estávamos usando a conta gratuita do sentry.io, mas o limite estourou e chegou a hora de termos nossa própria instância rodando no servidor secundário. Podemos fazer deployment da imagem Docker disponível em https://hub.docker.com/_/sentry/ e configurar as variáveis de ambiente.

**Comment by turicas** [comment]
Encontrei [esse repositório](https://github.com/mimischi/dokku-sentry) que já prepara tudo para subir uma instância do Sentry 9.x no dokku ([a versão 10 depende de muitas coisas extras e complexifica demais o deployment](https://github.com/mimischi/dokku-sentry/issues/12), por isso parece que ninguém ainda fez uma versão para deploy no dokku).

**Comment by berinhard** [comment]
Fechando essa issue aqui porque já estamos rodando uma insância do `dokku-sentry` e o brasil.io de produção já está se comunicando com ela com sucesso. Segue abaixo o print do teste que fiz segundo as instruções da documentação:

![Screenshot from 2020-06-26 12-49-37](https://user-images.githubusercontent.com/238223/85876302-e6effe80-b7ab-11ea-9676-8632249b909b.png)

E também o print do email recebi com o erro no Sentry:

![Screenshot from 2020-06-26 12-51-42](https://user-images.githubusercontent.com/238223/85876349-f2432a00-b7ab-11ea-888d-5f3a1db66c7b.png)

Já desativei a rota de debug que testei e agora [ela retorna 404](https://brasil.io/sentry-debug).
