### ISSUE TITLE
Bloqueio 429 Too Many Requests mesmo com não muitos requests

### ISSUE THREAD

**Issue by lubianat** [turicas/brasil.io#332]
Oi, gente, beleza?

Tou usando a API do Brasil.IO para baixar dados de covid-19 na cidade de São Paulo. A ideia é fazer isso todo dia, 1 vez por dia, pra alimentar umas visualizações simples. 

Meu código é simples no R, e tem 1 request, que eu mando manualmente (por agora). Ainda assim, recebi o bloqueio 429 por Too Many Requests. 

Alguma ideia de como posso resolver isso? 

Talvez seria interessante alguma forma mais clara deu conseguir entender o que deu errado. Talvez algo na documentação do Brasil.IO explicando os comprotamentos que levam ao 429? 

Obrigado!

EDIT:

Resposta da API: 
`Response [https://brasil.io/api/dataset/covid19/caso_full/data/?search=&date=&state=&city=S%C3%A3o+Paulo&place_type=&is_last=&city_ibge_code=&order_for_place=]
  Date: 2020-06-25 19:50
  Status: 429
  Content-Type: application/json
  Size: 792 B`

Ao menos um "Retry-after" poderia ser interessante

**Comment by lubianat** [comment]
Foi agora (depois de alguns minutos). Beleza. 

Ainda assim, vou deixar aberta a issue, para esse detalhe do "retry after" e para ficar registrado. 

Tranquilo fecharem a qualquer momento.

**Comment by berinhard** [comment]
Olá @lubianat, obrigado por abrir a issue! 

Na verdade, no payload do 429 vem um JSON com duas chaves: `message` e `available_in`. O primeiro tem como valor uma mensagem educativa sobre o uso da API. Percebemos que tem muita gente usando a API para baixar os dados completos quando, na verdade, é muito mais simples e menos oneroso para nossos servidores baixar o dataset completo na [listagem de datasets](https://brasil.io/datasets/). Inclusive, dá pra fazer isso com [a rows](https://github.com/turicas/rows) =)

O segundo valor é uma string no formato `"%d seconds"` que disponibiliza exatamente o número de segundos para que o cliente seja liberado novamente para novas requisições. Então, o retry after pode ser calculado utilizando esse valor.

De qualquer forma, obrigado pela issue e acho válido deixá-la aberta porque ainda vamos melhorar o controle de carga na API. Tivemos que ser "radicais" num primeiro momento porque as requisições para baixar todo o dataset estavam sendo abusivas, como falei acima.
