### ISSUE TITLE
Melhoras na página de boletins

### ISSUE THREAD

**Issue by berinhard** [turicas/brasil.io#333]
O PR #329 introduziu a página de [listagem dos boletins diários](https://brasil.io/covid19/boletins/) que é basicamente uma indexação das imagens que o @turicas estava divulgando pelo seu twitter até então. Essa página foi criada numa versão inicial para subrimir essa demanda, mas acredito que existam algumas melhorias que podemos introduzir para que ela escale bem.

**Qual o problema atual?**
As imagens da galeria apesar de parecerem thumbnails, não são de fato. São as próprias imagens finais respeitando um `width` em pixels no HTML. Essa estratégia inocente resolve o nosso problema atual de ter esse índice, mas não escala a longo prazo já que será necessário baixar **todas** as imagens de boletins (a página hoje tem 2.55 MB). Além disso, a interface está OK para 1 mês, mas pode começar a ficar confusa a partir dado que a pandemia infelizmente seguirá pelos próximos meses. 

**Sugestões de soluções**

1. Usar a templatetag [`regroup`](https://docs.djangoproject.com/en/3.0/ref/templates/builtins/#regroup) para organizar as imagens agrupadas por meses;
2. Carregar as imagens usando [lazyload](http://jquery.eisbehr.de/lazy/);
3. Adicionar uma lógica para gerar thumbnails **de fato** a partir da imagem original. Isso deverá ser ativado tanto após a pessoa adicionar um boletim via admin quanto via o comando [`manage.py update_bulletin`](https://github.com/turicas/brasil.io/blob/develop/covid19/management/commands/update_bulletin.py)

**Comment by turicas** [comment]
Para as miniaturas: podemos instalar o [thumbor](http://thumbor.org/) e usá-lo em todos os thumbnails - daí não precisamos lidar com isso no backend.
