### ISSUE TITLE
Erro 500 se planilha está em formato incorreto

### ISSUE THREAD

**Issue by turicas** [turicas/brasil.io#338]
Se tenho um arquivo CSV e salvo como "teste.xls" e tento importar como StateSpreadsheet, o sistema gera um erro 500 em vez de 4xx com uma mensagem de que a planilha não pode ser importada (nessa mensagem pode ter uma dica: verificar a extensão/formato e se não há fórmulas no arquivo).

**Comment by berinhard** [comment]
@turicas não consegui reproduzir esse erro 500 e nem encontrar referências a ele no novo Sentry. Tentei reproduzí-lo da seguinte forma:

1. Baixei o arquivo CSV modelo para o Acre;
2. Renomeei ele para `modelo-AC.xls` e tentei importar;
3. Não tive um erro 500, mas a exceção da rows abaixo que, inclusive fala sobre formato ou arquivo corrompida;

![Screenshot from 2020-06-29 11-30-57](https://user-images.githubusercontent.com/238223/86018866-49d7d480-b9fc-11ea-9c5c-5952f4f3218d.png)

O mesmo acontece quando renomeio o arquivo para a extensão `.xlsx`, mas com a seguinte mensagem de erro: `File is not a zip file`

**Comment by berinhard** [comment]
De qualquer forma, melhorei um pouco a mensagem de erro para informar a incoerência entre a extensão e o conteúdo da planilha.

![Screenshot from 2020-06-29 11-40-00](https://user-images.githubusercontent.com/238223/86019736-57da2500-b9fd-11ea-9e99-4ec4a7a06cde.png)
