### ISSUE TITLE
Dockerização do ambiente completo (dev|test|production)

### ISSUE THREAD

**Issue by jfunez** [turicas/brasil.io#34]
Atualmente temos um arquivo `docker-compose` para levantar um servidor de banco de dados.

Para facilitar o setup do ambiente sem ter que mexer com o **pyenv**, pensei em facilitar arquivos Dockefile* e docker-compose* para os ambiente de desenvolvimento, testing (Travis) e produção.
Neste caso a app django ficaria dentro de um container.

Para simplificar ainda mais, contaremos com um make file que tem instruções simples para: buildar, levantar, parar, ver logs, rodar tests, etc... Então no lugar de rodar comandos docker ... ou docker-compose ... ficaria algo tipo:

- `make dev_compose_build` para fazer docker build do stack
- `make dev_compose_up` para iniciar a app. **pronto**!
- `make dev_compose_stop` para parar todos os containers

**Comment by turicas** [comment]
Oi, @jfunez, você está trabalhando nessa issue?

**Comment by jfunez** [comment]
@turicas sim, espero terminar no fds

**Comment by turicas** [comment]
Implementada em 562c10f91c57313d4315443ff7e2a36507f42640.
