### ISSUE TITLE
Bloquear download de CSV sem filtros adicionais

### ISSUE THREAD

**Issue by berinhard** [turicas/brasil.io#344]
Essa issue surge em função da investigação das exceções `SystemExit` e tem relação com a issue #316 também.

Basicamente existem pessoas utilizando a querystring `/dataset/{slug}/{tablename}/?format=csv` para baixar algum dataset completo. Como o Django renderiza o CSV no backend, estamos tomando muitos erros por conta do timeout do gunicorn. 

Portanto a ideia é: não permitir usar `?format=csv` caso outros filtros não estejam habilitados (ou seja, na interface o botão "BAIXAR COMO CSV" não vai aparecer caso a pessoa entre no dataset e não faça nenhum filtro -- o que quer dizer que não terá outra query string).

- [ ] Ativar/desativar botão de download no frotend no caso de ter filtros
- [ ] Invalidar o form no backend no caso de download de CSV sem nenhum tipo de filtro adicional

**Comment by endersonmaia** [comment]
Configurar o Page Rules do CloudFlare pra fazer cache disso aí, não resolveria ?

`/dataset/*/*/?format=csv` =>  `Cache Everything`

acho que vale o teste e delega isso pro CloudFlare enquanto vcs resolvem no backend de forma mais definitiva

**Comment by endersonmaia** [comment]
talvez esse `?` precise de escaping, pra não pegar no matching do Page Rule

https://support.cloudflare.com/hc/en-us/articles/218411427#understand-wildcard-matching-and-referencing

**Comment by turicas** [comment]
@endersonmaia acho que pode resolver, mas parcialmente. O problema é que essa funcionalidade foi criada pensando em pessoas que não são programadoras (que não podem baixar o dataset completo pelo fato de ser muito grande e não abrir num software de planilhas eletrônicas, ou pelo fato de não terem conhecimentos de programação para usar a API), porém o que acontece é que essa é uma chamada custosa ao backend e está sendo "abusada" por pessoas que poderiam simplesmente baixar o .csv.gz de data.brasil.io (que é um servidor de arquivos estáticos e não impacta no backend da plataforma) ou simplesmente usando a API.
Enfim, enquanto esse caso de uso (baixar o CSV completo) não estava atrapalhando o uso do site, não via problemas em deixar ele liberado (inclusive sem autenticação), o problema é quando começaram a fazer isso excessivamente (sem ler a documentação que está escrita/linkada na própria página). De certa forma, essa mudança é, também, para educar a quem está usando a plataforma de maneira automatizada.

**Comment by endersonmaia** [comment]
eu entendi o problema, inclusive eu havia sugerido no chat um `rewrite` (/tabela/?format=csv => tabela.tar.gz) mas não faz muito sentido sentido pois os retornos são diferentes

o que proponho aqui é usar o cache do CloudFlare mesmo, já que na issue #341 vi que as APIs não estão entrando no cache do CloudFlare

**Comment by endersonmaia** [comment]
concordo que há um fator pedagógico aí, pra o pessoal aprender a usar o recurso certo

😄

**Comment by turicas** [comment]
> o que proponho aqui é usar o cache do CloudFlare mesmo, já que na issue #341 vi que as APIs não estão entrando no cache do CloudFlare

Pelo que analisei o CloudFlare não está cacheando porque estamos mandando o header `Vary` com valores incorretos. Acho que é melhor a longo prazo é corrigirmos isso no código do que ter configurações (que não estão explícitas) em outros sistemas. Mas se continuar acontecendo e não conseguirmos consertar num tempo hábil, daí faz sentido sua sugestão. :)

**Comment by berinhard** [comment]
Pontos extras do @turicas sobre essa issue

 1- é importante que uma página de erro 4xx seja exibida se a pessoa passar somente ?format=csv (ou mesmo que ela passe outras querystrings, mas com valores vazios -- isso acontece se ela submeter o form sem preencher nada, ex: ?search=&is_last=&format=csv). essa página deve ser uma página HTML com o base.html do brasil.io, mas sem toda a "parafernalha" do dataset. a mensagem deve ser uma mensagem bem didática, explicando que essa não é a melhor forma de se fazer isso e linkando para a URL de download que está no Version desse dataset (isso aqui é muito importante). 

 2- em vez de ocultarmos o botão "BAIXAR DADOS EM CSV" no caso de não ter filtros no formulário, devemos substituí-lo por um botão "BAIXAR DADOS COMPLETOS EM CSV" , que direciona o usuário para o download_url daquela Version. Assim o botão não vai "sumir" para quem está acostumado e a pessoa vai conseguir cair na página correta de onde precisa baixar 

 o que estou pensando é no seguinte fluxo: A- a pessoa roda o script dela, que vai dar erro 4xx. se ela entrar na página 4xx, já vai conseguir ler e entender o problema. B- se a pessoa não entrar na página que deu 4xx, ela vai entrar na página do dataset e clicar no botão pra pegar o "link correto", daí vai cair na página correta de baixar o CSV completo
