### ISSUE TITLE
Adicionar disclaimer ao HTML base do DRF

### ISSUE THREAD

**Issue by berinhard** [turicas/brasil.io#346]
Para diminuir o volume de requisições abusivas (ver #316 e #344 para mais contexto), gostaríamos de ter uma mensagem no template base do DRF (exemplo de [/api/datasets](https://brasil.io/api/datasets/)) alertando as pessoas para usarem o data.brasil.io correspondente ao dataset para baixá-lo todo.

Usar o [texto de exceção](https://github.com/turicas/brasil.io/blob/develop/api/handlers.py#L4) de throttling como base.

**Comment by turicas** [comment]
Adendo: todo objeto `Version` ligado a um dataset possui uma URL pra download (nem sempre essa URL é a do data.brasil.io - porque ainda estou migrando do Google Drive pra lá). Seria legal indicar essa URL e não uma genérica.
