### ISSUE TITLE
Precisão da linguagem: casos x casos confirmados

### ISSUE THREAD

**Issue by lubianat** [turicas/brasil.io#350]
Fala, pessoal, beleza?

Reparei que em alguns locais do painel e das divulgações os dados são divulgados como "casos" e "óbitos" por COVID-19. Apesar desse ser  o padrão da mídia, isso não é preciso. 

O número de casos em São Paulo, por exemplo, é por volta de [8 vezes o número de casos confirmados ](https://g1.globo.com/sp/sao-paulo/noticia/2020/06/23/cidade-de-sp-pode-ter-12-milhao-de-infectados-pelo-coronavirus-aponta-mapeamento-da-prefeitura.ghtml). 

Sendo o Brasil.IO um protal com bastante acesso, acredito que seria interessante usar os termos precisos. A forma que os dados são apresentados altera a percepção da gravidade do problema. 

Sugiro mudanças simples: 
*  Evitar em todo lugar o uso simples de "casos" ou "óbitos" 
*  Usar no lugar "casos confirmados" & "óbitos confirmados"; ou até, para ser mais preciso, "casos notificados" e "óbitos notificados". 

Gosto da palavra "notificados" por que deixa claro que os números representam  dados que entraram no sistema de saúde, e sugere (de forma correta) que ocorreram óbitos e casos não notificados. 

Fica a sugestão e, de novo, parabéns pelo trabalho.

**Comment by turicas** [comment]
Oi, @lubianat, obrigado pela sugestão. Transferi a issue para o repositório correto.
Em vários dos lugares que usamos apenas "casos" é por questões de espaço. Não tenho tempo agora de mudar e ficar ajustando o CSS para caber tudo onde deveria.
Se você puder, liste os locais exatos onde poderíamos mudar e crie um PR que revisarei, ok?

**Comment by turicas** [comment]
Vou fechar por inatividade.
