### ISSUE TITLE
Problema de CSS no menu no Firefox

### ISSUE THREAD

**Issue by turicas** [turicas/brasil.io#354]
Testei no Google Chrome e abre corretamente.

![erro-firefox](https://user-images.githubusercontent.com/186126/86662500-25af6100-bfc3-11ea-8542-1c556d16b920.png)

**Comment by marcmatias** [comment]
Para mim esse bug ta acontecendo tanto no chrome quanto no FF 

![image](https://user-images.githubusercontent.com/26860387/86663928-9905a280-bfc4-11ea-8783-d0ac5eb10712.png)

De todo modo eu já corrigi esse bug aqui #351 na proposta de melhorias do front.

Agora está assim rodando em minha máquina:

![image](https://user-images.githubusercontent.com/26860387/86664221-e124c500-bfc4-11ea-9582-9e66b81a1f55.png)

**Comment by rniguel** [comment]
O menu verde você fala né???

Tenta colocar todos esses items dentro de uma section com width de 1200px e display: flex com justify-content: center;

Ai dentro você coloca outra div, com display: flex, flex-direction: row, align-tems: center

Acho que isso resolve o problema do bug talvez, não sei, teria que postar o código tbm né :/

**Comment by rniguel** [comment]
![image](https://user-images.githubusercontent.com/48338011/87460386-2eb3ba00-c5e3-11ea-9c25-72d80ac3f5e9.png)

`
   /*Na div que envolve esses botões*/
    display: contents;
    flex-direction: row;
`

`
    /*EM CADA BOTÃO*/
    margin: 5px
`

**Comment by turicas** [comment]
Fechando porque já foi corrigido.
