### ISSUE TITLE
Gerenciar os arquivos estáticos das bases de dados a partir do Django

### ISSUE THREAD

**Issue by berinhard** [turicas/brasil.io#357]
Precisamos gerenciar no Django os arquivos estáticos disponíveis para download em um dataset. o core precisa gerar automaticamente (e subir) as páginas _meta/list.html que estão no data.brasil.io. Vejo que para isso precisamos criar um model TableFile, que conterá a informação sobre cada tabela. Sempre que um novo TableFile for adicionado, o backend deverá gerar novamente o _meta/list.html do dataset inteiro, o SHA512SUMS e subí-lo para data.brasil.io. Para que o processo continue funcionando sem conflito com o que temos hoje, é necessário que eu consiga executar de maneira automatizada a adição de um arquivo desses, seja via management command ou API. Talvez aqui o ideal seja eu (como cliente) subir o arquivo que quero adicionar para algum lugar (pode até ser no data.brasil.io, mas em um outro diretório, não sendo o diretório final onde ficará o arquivo), daí a API/management-command faria o seguinte (talvez compense fazer isso com streaming, de forma a não salvar o arquivo no disco): 

A- baixaria o arquivo, 
B- geraria o SHA512SUM do arquivo, 
C- subiria o arquivo para o destino final no data.brasil.io, 
D- criaria o registro TableFile, 
E- geraria a nova listagem, 
F- subiria a nova listagem. se a URL do arquivo que o cliente providenciar tiver a mesma base que a URL de destino do arquivo (ex: subo para data.brasil.io/temp/caso.csv.gz e o destino será calculado automaticamente pelo backend como data.brasil.io/dataset/covid19/caso.csv.gz) 

Então os itens A-C poderiam ter uma otimização de rodar um comando "s3 mv" em vez de baixar/subir o arquivo (isso vai agilizar demais o deploy de dados - boa parte do processo atual é baixando e subindo novamente).

**Comment by berinhard** [comment]
@turicas apesar de achar a ideia do streaming ideal fiquei na dúvida sobre como eu seria capaz de determinar o tamanho do arquivo via streaming já que provavelmente o arquivo estará compactado num `.csv.gz`, certo?

Minha pergunta vem como base no [código atual](https://github.com/turicas/brasil.io/blob/develop/data-server/generate_list.py#L57) para gerar os HTMLs dos arquivos brutos.

**Comment by berinhard** [comment]
Tenho uma outra pergunta também sobre o model `TableFile` ele seria algo como:

```python
class TableFile(models.Model):
    table = models.ForeignKey('core.Table')
    file_url = models.URLFIeld()
    sha512sum = models.CharField(max_length=128)
    filename = models.CharField(max_length=100)
    size = models.BigIntegerField()  # não sei se só um IntegerField dá conta, gostaria da sua opinião
```

Então no caso do [Covid-19](https://data.brasil.io/dataset/covid19/_meta/list.html), por exemplo, teríamos 4 entradas nessa tabela, certo? Nessa página, da onde poderíamos pegar a informação de `Data de captura`? Podemos simplesmente usar a `table.import_date` mais recente?

Vamos precisar de uma migração de dados inicial também, certo? Assim, se você quiser atualizar a tabela de `casos` e `casos_full` sem atualizar a de óbitos, o sistema poderia dar conta de gerar o HTML. Faz sentido isso?

**Comment by turicas** [comment]
> @turicas apesar de achar a ideia do streaming ideal fiquei na dúvida sobre como eu seria capaz de determinar o tamanho do arquivo via streaming já que provavelmente o arquivo estará compactado num `.csv.gz`, certo?

A ideia é fazer tudo durante o processo de streaming (eu não sei se é possível com o minio, mas provavelmente é). Segue um esboço de como acho que o código poderia ficar, mas não pesquisei as funções de streaming e rename - provavelmente as funções de streamming reader/writer virão de lugares diferentes: a reader pode vir da requests [ou da rows](https://github.com/turicas/rows/blob/develop/rows/utils.py#L384) e a de escrita provavelmente virá do minio-django:

```python
import hashlib
from urllib.parse import urlparse

from xxx import stream_file, rename_s3_file  # TODO: implement


def process_file(dataset_slug, tablename, input_url):
    chunk_size = 8 * 1024 * 1024  # TODO: get from `settings`
    s3_endpoint = "data.brasil.io"  # TODO: get from `settings`
    bucket_name = "dataset"  # TODO: get from `settings`
    remote_filename = f"{dataset_slug}/{tablename}.csv.gz"
    output_url = f"https://{s3_endpoint}/{bucket_name}/{remote_filename}"

    # Check if destination S3 server is the same for the download static server
    destination_to_same_download_s3 = urlparse(input_url).netloc == urlparse(output_url).netloc
    hasher = hashlib.sha512()
    file_size = 0

    if destination_to_same_download_s3:  # we can just rename the file after processing, no need to re-upload
        # TODO: find compatible stream function -- this was taken from my head
        # TODO: find compatible S3 rename function -- this was taken from my head
        stream_reader = stream_file(input_url, mode="rb")
        while True:
            chunk = stream_reader.read(chunk_size)
            if not chunk:
                break
            file_size += len(chunk)
            hasher.update(chunk)
        rename_s3_file(input_url, output_url)

    else:  # external static server, needs to download and upload
        # TODO: find compatible stream functions -- these were taken from my head
        stream_reader = stream_file(input_url, mode="rb")
        stream_writer = stream_file(s3_endpoint, bucket_name, remote_filename, mode="wb")
        while True:
            chunk = stream_reader.read(chunk_size)
            if not chunk:
                break
            stream_writer.write(chunk)
            hasher.update(chunk)
            file_size += len(chunk)
    file_hash = hasher.hexdigest()
    return output_url, file_size, file_hash

# case 1: same s3 server
internal_input_url = "https://data.brasil.io/temp-upload/caso.csv.gz"  # this URL is passed by the client
process_file("covid19", "caso", internal_input_url)

# case 2: external static server
external_input_url = "https://static.example.com/caso.csv.gz"  # this URL is passed by the client
process_file("covid19", "caso", external_input_url)
```

**Comment by turicas** [comment]
> Tenho uma outra pergunta também sobre o model `TableFile` ele seria algo como:
> 
> ```python
> class TableFile(models.Model):
>     table = models.ForeignKey('core.Table')
>     file_url = models.URLFIeld()
>     sha512sum = models.CharField(max_length=128)
>     filename = models.CharField(max_length=100)
>     size = models.BigIntegerField()  # não sei se só um IntegerField dá conta, gostaria da sua opinião
> ```

Adiciona também `created_at`.


> Então no caso do [Covid-19](https://data.brasil.io/dataset/covid19/_meta/list.html), por exemplo, teríamos 4 entradas nessa tabela, certo?

Sim.


> Nessa página, da onde poderíamos pegar a informação de `Data de captura`? Podemos simplesmente usar a `table.import_date` mais recente?

Não. `import_date` é a data que executamos o `import_data` (ou seja, a data que disponibilizamos os dados no Brasil.IO), não a data em que capturamos os dados (elas tendem a ser divergentes principalmente em grandes datasets).
Esse é um problema da atual estrutura: nós não temos `collect_date` a nível de `Table`, apenas a nível de `Version` (e por enquanto, para reduzir a complexidade, temos apenas um `Version` por `Dataset`). O ideal seria termos um `Table.collect_date` também (e caso ele não esteja preenchido, fazer fallback para `table.dataset.<last-active-version>.collect_date`).


> Vamos precisar de uma migração de dados inicial também, certo? Assim, se você quiser atualizar a tabela de `casos` e `casos_full` sem atualizar a de óbitos, o sistema poderia dar conta de gerar o HTML. Faz sentido isso?

Faz sentido, mas acho que não precisamos da migração de dados: eu posso rodar manualmente o comando que sobe esses arquivos para cada dataset (a página `_meta/list.html` ainda não existe para todos os datasets - alguns ainda estão no Google Drive e prefiro ter o controle manual por enquanto).

**Comment by berinhard** [comment]
Valeu pelos comentários @turicas! Me ajudou bastante a entender as coisas aqui =)

**Comment by berinhard** [comment]
Script de referência: https://github.com/turicas/covid19-br/blob/master/deploy.sh

**Comment by berinhard** [comment]
Update sobre isso: o Minio está me parecendo bem limitado no que diz respeito ao upload da forma que estamos pensando.

A API deles implementa somente dois métodos para upload de arquivos: [`put_object`](https://github.com/minio/minio-py/blob/master/examples/put_object.py) e [`fput_object`](https://github.com/minio/minio-py/blob/master/examples/fput_object.py). Ambas as funções precisam saber previamente, seja em memória ou via arquivo em disco, todo o conteúdo do arquivo. Estudando o código, vi aqui que existe uma função auxiliar eventualmente utilizada por esses métodos que é a [`_stream_put_object`](https://github.com/minio/minio-py/blob/d4f0bde6da09c16013e38f23c93e9428f25eec97/minio/api.py#L1777). Mas, apesar do nome, essa função também precisa ter todo o conteúdo do arquivo na mão para dividir internamente o [upload por threads](https://github.com/minio/minio-py/blob/d4f0bde6da09c16013e38f23c93e9428f25eec97/minio/api.py#L1815).

Como dá para ver pelo código deles, nós teríamos que praticamente copiar a API deles para fazermos nós mesmos esse controle de escrita. @turicas como isso me parece trabalho e arriscado (tem todo um controle de estado para uploads que foram completados vs ainda pendentes, por exemplo), queria alinhar contigo sobre essa estratégia. Por enquanto, só estou vendo esse caminho mesmo como solução, mas queria ver contigo se isso vale a pena.

A outra alternativa seria escrever o arquivo todo em disco para usar os métodos tradicionais de upload de arquivo. Está me parecendo mais simples fazer esse controle do arquivo em disco (download no `/tmp`, upload p/minio, remover o arquivo temporário) do que manter em código o controle do upload por pedaço com o Minio. O que você acha?

**Comment by berinhard** [comment]
Ah estou trabalhando no branch `feature/import-dataset-files` e o código atual está em `core/commands.py`. O comando de teste que estou usando é:  `python manage.py update_table_file covid19 obito_cartorio https://data.brasil.io/dataset/covid19/obito_cartorio.csv.gz`
