### ISSUE TITLE
Sistema invalida planilha completa quando admin cria planilha de totais automaticamente

### ISSUE THREAD

**Issue by turicas** [turicas/brasil.io#374]
Quando uma pessoa (covid19-admin) aperta o botão `UpdateStateTotals` e o sistema gera uma planilha total para o estado X e essa pessoa já tem uma planilha ativa para o mesmo estado no mesmo dia com dados completos, a planilha completa fica inativa e, quando uma outra pessoa sobe uma planilha completa para o mesmo estado ela não dá match (porque a ativa tem somente os totais).
Possíveis soluções: 
1. Se a pessoa possuir uma planilha ativa que só tenha o total e uma inativa completa, podemos considerar essa inativa como ativa também na hora da busca por planilhas durante o processo de checagem (talvez tenham que fazer a checagem extra de validar se os totais da planilha ativa e da inativa são iguais, para que a completa possa substituir a total com segurança);
2. Criar um usuário específico para esses uploads e usá-lo sempre (talvez adicionar como warning o username de quem apertou o botão) -- como eu quase nunca subo planilhas, poderia ser o meu usuário por enquanto, mas pode ser algum de sistema também (como o "robô" do chat);

**Comment by berinhard** [comment]
Acho a 1 meio ruim porque é mexer numa estrutura que sabemos que tá operando bem e estável hoje. Me parece mais interessante fazer a estratégia número 2. Isso vai facilitar, inclusive, na hora de buscarmos quais as planilhas ques foram importadas pelo processo de atualização de totais.

**Comment by turicas** [comment]
De acordo. Você implementa então com essa abordagem?

**Comment by berinhard** [comment]
Já estou implementando hehehe! A flag de #375 ajudou nesse processo aqui.
