### ISSUE TITLE
Problema na instalação de dependências do ambiente virtual Python

### ISSUE THREAD

**Issue by hilam** [turicas/brasil.io#388]
Ao tentar criar o ambiente virtual Python para o projeto, utilizando Python 3.6, levanta um problema com a versão não pinada do ipython:

![python36](https://user-images.githubusercontent.com/1016703/91660503-bc246e00-eaac-11ea-9aa5-5c515b091edd.png)

Tentei então um ambiente virtual com Python 3.7 e levantou um problema na biblioteca dataclasses.

![python37](https://user-images.githubusercontent.com/1016703/91660526-dfe7b400-eaac-11ea-85d3-4bbd006b5169.png)

Qual a melhor abordagem pra resolver? 

1) Pinar a versão do ipython? (mais simples)
ou
2) Passar a usar a versão 3.7 do Python, que já tem "dataclasses", o que poderia substituir o uso atual da biblioteca "dataclasses"

Para qualquer dos casos, estou disposto a ajudar.

**Comment by turicas** [comment]
Como o projeto requer Python 3.7+, acho que podemos remover a dependência em dataclasses. Se você removê-la dos `requirements.txt` a instalação roda com sucesso?

**Comment by hilam** [comment]
Sim, consigo instalar o ambiente, e levantar os containers, mas ao rodar os testes, retorna erro por falta do módulo "asgiref". 

Depois de instalá-lo manualmente, consigo rodar os testes (resulta uma falha num assert em covid19/tests/test_forms.py, que ainda não identifiquei o motivo ainda; talvez porque não tenha feito o "update_data"). 

Creio ser o caso de retirar "dataclasses" e incluir o "asgiref" no requirements.txt. E se o projeto já requer Python 3.7+, acho que seria o caso, também, de mudar as menções ao Python 3.6 no arquivo docs/dev-setup.md

**Comment by berinhard** [comment]
Olá @hilam valeu pela pesquisa e sugestões. Tô de acordo que o caminho que você propõe é o ideal, inclusive com a atualização da documentação. Você poderia abrir um PR com isso? Os testes em CI [já estão rodando com Python 3.7](https://github.com/turicas/brasil.io/blob/develop/.github/workflows/django.yml#L14), então podemos ter uma segunda validação para enteder os erros com os testes.

**Comment by hilam** [comment]
PR submetido, @berinhard
