### ISSUE TITLE
Usar ou não usar / no final das URLs?

### ISSUE THREAD

**Issue by dukex** [turicas/brasil.io#4]

**Comment by dukex** [comment]
Eu acho desnecessário! Afinal o final da url deveria ser sempre o formato do arquivo

**Comment by filhodanuvem** [comment]
Concordo! O que faz desnecessária aquela querystring "?formato=" também.

**Comment by dukex** [comment]
@cloudson foi o que comentei na issue https://github.com/turicas/api.brasil.io/issues/5

**Comment by filhodanuvem** [comment]
Boa!

**Comment by turicas** [comment]
@rodsenra comentou por e-mail que não costuma usar, mas não disse por quê.

Conversando com @rhcarvalho, chegamos à conclusão de que pareceria mais "semântico" se coleções, por padrão, terminassem com `/` no final e instâncias dessas coleções não, remetendo a diretórios e arquivos em um sistema de arquivos. Porém, essa regra seria o que a API usaria para criar novas URLs e embutí-las nos documentos, mas por questões de facilidade de uso (exemplo: o desenvolvedor está navegando na API pelo seu navegador para descobrir novos recursos, verificar o formato dos dados etc.) a API deveria aceitar requisições em ambos formatos. Acho que essa abordagem é a que faz mais sentido.
