### ISSUE TITLE
Criar model Proxy para operar em cima das tabelas dinâmicas com semântica de domínio

### ISSUE THREAD

**Issue by berinhard** [turicas/brasil.io#401]
Os PRs #395 e #393 adicionaram uma flexibilidade importante ao código que é podermos configurar como o [model dinâmico é criado](https://github.com/turicas/brasil.io/blob/develop/core/dynamic_models.py#L83) especificando, entre outras coisas, seus managers ou querysets. Isso é excelente porque agora conseguimos ter um código semântico e desacoplado do funcionamento dinâmico do banco de dados.

Com primeiro experimento de customização, criamos o arquivo [`core/data_models.py`](https://github.com/turicas/brasil.io/blob/develop/core/data_models.py) com a implementação de métodos com semântica de domínio para operar em cima das tabelas de empresa e atualizamos o método `Table.get_model` para [forçar o uso dessas customizações](https://github.com/turicas/brasil.io/blob/develop/core/models.py#L350). 

Apesar de funcional, essa abordagem gera alguns problemas a longo prazo:

1. Ainda mantemos outras partes do código do brasil.io ciente do funcionamento dos modelos dinâmicos por conta de métodos e funções como a própria `Table.get_model` e também [`get_table_model`](https://github.com/turicas/brasil.io/blob/develop/core/models.py#L439);
2. Refatorações de nomes no banco, como no PR #393, se tornam trabalhosas e arriscadas porque a relação fica espalhada pelo código;
3. É difícil de começar a testar views que usem os bancos dinâmicos porque não temos como mockar de maneira simples seus funcionamentos;

Para isso, sugiro como refatoração criarmos model Proxyes no módulo `core/data_models.py` que de alguma forma pudessem customizar a construção dos models. Algo como:

```python
from brasilio.core.models import Table

class EmpresaTable(Table):

    def get_mixins(self):
        mixins = [SociosBrasilEmpresaMixin]

    def get_managers(self):
        return {"objects": SociosBrasilEmpresaQuerySet.as_manager()}

    class Meta:
        proxy = True
        dynamic_table_name = 'empresa'
        dynamic_dataset_slug = 'socios-brasil'
```

Assim, com a criação de também um manager customizado para o nosso model de `Table` que olharia para `self.model._meta.dynamic_table_name` e `self.model._meta.dynamic_dataset_slug`, poderíamos ter uma usabilidade como:

```python
from brasilio.data_models import EmpresaTable

document = "algum CNPJ"
Empresa  = EmpresaTable.objects.get_model()
print(Empresa.objects.get_headquarter_or_branch(document)
```

**Comment by turicas** [comment]
Comecei a esboçar uma solução em https://github.com/turicas/brasil.io/tree/enhancement/refactor-dynamic-models-queryset (c300fb5d2a954530f44544113f85fca823675b45).

**Comment by berinhard** [comment]
Possível caminho:

- Model proxy `EmpresaTableConfig` herdar de outro proxy base, algo como, `TableConfig`;
- Esse model proxy iria forçar a implementação dos métodos `get_mixins` e `get_managers`, por exemplo;
- O proxy model `TableConfig` iria implementar um `classmethod` `get_model` responsável por retornar o modelo dinâmico descrito pela tabela;

**Comment by berinhard** [comment]
Só para documentar, infelizmente adicionar atributos customizáveis ao `Meta` do model não rola. Apesar de aceito, o [ticket 5793](https://code.djangoproject.com/ticket/5793) do Django que trata sobre isso parece ainda não ter um encaminhamento claro.

**Comment by turicas** [comment]
> Só para documentar, infelizmente adicionar atributos customizáveis ao `Meta` do model não rola. Apesar de aceito, o [ticket 5793](https://code.djangoproject.com/ticket/5793) do Django que trata sobre isso parece ainda não ter um encaminhamento claro.

Acho que é mais um motivo para *não* usarmos proxy models e criarmos uma classe nossa - que pode ter uma subclasse `Meta` com o que quisermos (apenas para seguir o padrão do Django).
