### ISSUE TITLE
Adicionar um favicon no sistema de administração

### ISSUE THREAD

**Issue by diegobiavati** [turicas/brasil.io#428]
Adicionar um favicon no sistema de adiministração.

![image](https://user-images.githubusercontent.com/572651/93460792-2a916a80-f8ba-11ea-97e0-30e0cfb2641f.png)

**Comment by diegofsousa** [comment]
Já existe um arquivo "favicon.ico" para o admin?

**Comment by monteirocamis** [comment]
posso ajudar nessa issue mas nao achei aonde que ta sem favicon.. se ainda precisarem me avisem aqui por favor ;)

**Comment by diegobiavati** [comment]
> posso ajudar nessa issue mas nao achei aonde que ta sem favicon.. se ainda precisarem me avisem aqui por favor ;)

No módulo de  admin do Django.

**Comment by Riverfount** [comment]
Tô trabalhando nessa!
