### ISSUE TITLE
Tornar o cadastro de usuárias mais verificável

### ISSUE THREAD

**Issue by berinhard** [turicas/brasil.io#433]
Essa tarefa surge para viabilizar a entrega da issue #427 

A ideia é tornarmos o processo de cadastro de issues menos burlável. Para isso, precisamos:

- [x] Adicionar captch ao formulário de cadastro (usar o mesmo do [formulário de contato](https://brasil.io/contato))
- [ ] Ativar verificação por email (provavelmente o processo de [ativação em 2-passos](https://django-registration.readthedocs.io/en/3.1.1/activation-workflow.html) da app Django Registration dá conta do recado)

**Comment by berinhard** [comment]
@turicas só para deixar explícito: a app Django em produção já possui o envio de email configurado? (95% que sim, mas queria confirmar)

**Comment by turicas** [comment]
> @turicas só para deixar explícito: a app Django em produção já possui o envio de email configurado? (95% que sim, mas queria confirmar)

Sim, via Sendgrid.
