### ISSUE TITLE
Corrigir problema de duplicidade de meta informações em Table e Field

### ISSUE THREAD

**Issue by berinhard** [turicas/brasil.io#440]
Hoje existem duas informações que hora estão no model `Table` e hora no model `Field`:

- **Filtragem**: algumas tabelas possuem uma lista com `filtering` enquanto outras entradas de `Field` com uma flag sinalizando que são campos que dispõem filtros;
- **Busca**: o mesmo acontece aqui

O objetivo é definir o model `Field` como o único responsável por tal controle e averiguação. Como refatoração, poderíamos criar properties no model `Table` como `Table.filtering_fields` ou `Table.searching_fields` que operassem em cima dos seus `Fields`.

**IMPORTANTE**: para trabalhar nessa issue, é aconselhável utilizar o dump de metadados do que temos hoje em prod. O comando `export_fields_to_csv` e `import_fields_from_csv` podem ser úteis nesse sentido.

**Comment by berinhard** [comment]
@turicas, só para confirmar, rodar o `python manage.py update_fields_from_csv brasilio-fields.csv` com o arquivo resultante do `export_fields_to_csv` serve também, né!?

**Comment by turicas** [comment]
> @turicas, só para confirmar, rodar o `python manage.py update_fields_from_csv brasilio-fields.csv` com o arquivo resultante do `export_fields_to_csv` serve também, né!?

Sim, na verdade o nome correto do comando é o `update_fields_from_csv` (o `import_fields_from_csv` citado na descrição não existe, foi errado - era `update` em vez de `import`).
