### ISSUE TITLE
Criar teste para listagem de dados

### ISSUE THREAD

**Issue by turicas** [turicas/brasil.io#462]
O PR #455 introduziu um bug, corrigido em 1136219a84408f0f60872c8c06793cf3ac551851, que fez com que os dados não fossem mais listados por conta da falta de uma variável no template. Precisamos criar testes para cobrir essa parte do código e, se possível, habilitar automaticamente alguma flag de execução dos testes para encontrar variáveis em templates que não estão definidas.

**Comment by berinhard** [comment]
Fechando essa issue pq o PR #465 já resolveu
