### ISSUE TITLE
Domínio sob o .br

### ISSUE THREAD

**Issue by fbobraga** [turicas/brasil.io#471]
Não é conveniente um domínio sob o .br (e algo typo um https://en.wikipedia.org/wiki/CNAME_record pra redirecionar?

Dava até pra pedir colaboração do CGI.br ou registro.br

**Comment by fbobraga** [comment]
Com domínio sobre .br dá pra levantar CPF/CNPJ de responsável com um simples whois

**Comment by turicas** [comment]
@fbobraga para que você quer meu CPF? Trocar o domínio nesse momento não vai nos trazer nenhum ganho, só trabalho e gastos. Além disso, o site já é conhecido por esse nome, tem toda a identidade visual baseada nele. Essa ideia não faz sentido.

**Comment by fbobraga** [comment]
não é querer seu CPF: não precisa estar registrado com ele... só fechar sem discutir com os demais participantes do grupo é a solução então?

**Comment by fbobraga** [comment]
mas:
![Sem título](https://user-images.githubusercontent.com/3438006/95605887-f3812580-0a2f-11eb-82c6-6b39ef52381a.png)

**Comment by turicas** [comment]
Eu sei que posso registrar usando um CNPJ no registro.br. Mas eu não quero trocar o domínio do projeto e já expliquei isso acima, aceite isso.
O fato do projeto ser aberto/feito de forma colaborativa não quer dizer que qualquer um possa entrar aqui e tomar a decisão que quiser. Com sua insistência nesse ponto você está mais atrapalhando que ajudando (eu poderia estar usando o tempo que escrevo essas respostas para atualizar um dataset que você mesmo identificou estar desatualizado).
