### ISSUE TITLE
Not Found ao clicar em um CNPJ a partir da busca de empresas

### ISSUE THREAD

**Issue by anapaulagomes** [turicas/brasil.io#497]
Ao realizar uma busca como [essa](https://brasil.io/dataset/socios-brasil/socios/?search=&cnpj=&razao_social=&nome_socio=CARLOS+MEDEIROS+MIRANDA&tipo_socio=&qualificacao_socio=) (página de sócios) o resultado é uma lista de empresas com seus respectivos CNPJs. Ao clicar no CNPJ a página é redirecionada para uma página que não existe (exemplo [aqui](https://brasil.io/especiais/documento/05725903000153/)).

**Comment by turicas** [comment]
Obrigado por relatar! O problema foi corrigido (os links que você citou já estão abrindo), porém a solução que usei não é a definitiva. Por conta da limitação em criar índices compostos na importação de dados atual, eu preciso criar manualmente alguns índices quando importo esses dados e nem todos foram criados da última vez, o que deixa essa consulta bem lenta e, no fim das contas, gera um 404 (era pra ser algum erro 5xx, mas por algum motivo o dokku está gerando 404 para o gateway timeout).
Já existe uma issue relatando o problema: #461.
