### ISSUE TITLE
Problema no uso da interface Web da API

### ISSUE THREAD

**Issue by turicas** [turicas/brasil.io#499]
Detectei um problema que aconteceu desde que migramos o domínio e a autenticação ao mesmo tempo. Mesmo que estejamos autenticados em `brasil.io`, ao acessarmos pelo navegador um endereço da API (exemplo: https://api.brasil.io/v1/dataset/covid19/) ela não detecta que estamos autenticados a sempre recebemos a mensagem de erro "As credenciais de autenticação não foram fornecidas ou estão inválidas.".

**Comment by berinhard** [comment]
Resolvi o código com esse commit 1a79403bae2e18be8bc231c595e09a32b32ce20d permitindo configurar o [`SESSION_COOKIE_DOMAIN`](https://docs.djangoproject.com/en/3.1/ref/settings/#session-cookie-domain) via variável de ambiente. 

Tô fazendo o deploy para depois setar para `.brasil.io` porque isso funciona como wildcard para os subdomínios compartilhar das sessões dos users também.

**Comment by turicas** [comment]
Variável configurada e deploy feito. Precisei deslogar e logar novamente, mas funcionou. =)
