### ISSUE TITLE
Suportar ?format=jsonld|rdf|csv?

### ISSUE THREAD

**Issue by dukex** [turicas/brasil.io#5]

**Comment by dukex** [comment]
query string do formato sai fora da idéia do REST, acho que esses formatos são interessantes mas não vejo com uma prioridade

**Comment by turicas** [comment]
A ideia de suportar outros formatos de saída é facilitar o uso em outros softwares ou por usuários não-programadores (exemplo: CSV).

Eu não sei o quanto isso "foge" da filosofia REST, visto que (na minha visão) _query strings_ devem ser usadas para modificar o conteúdo do recurso que será devolvido. A adição de `?formato=` seria apenas para **facilitar o uso** da API, fazendo com que recursos pudessem ser facilmente linkados em qualquer site, com representação direta em formatos que não o JSON-LD. O fato de suportar isso não quer dizer que não seria suportada alteração do formato de saída através de requisição pelo `Content-Type`.

**Comment by dukex** [comment]
E por que não usar o formato no final do arquivo? .csv .rdf etc?

**Comment by turicas** [comment]
@dukex, isso é "menos REST" do que usar `?format=csv`, já que você estará alterando o **nome do recurso HTTP** (que, na verdade, _é o mesmo_, você só está pedindo que esse mesmo recurso seja _representado em outro formato_).

**Comment by rennerocha** [comment]
Se for seguir REST a risca, o formato retornado deveria ser de acordo com o header _Accept_ enviado pelo cliente. Mas usar uma _query string_ pode facilitar seu uso para um público maior (e menos conhecedor de headers de HTTP).

**Comment by turicas** [comment]
@rennerocha, como comentei: a ideia é só facilitar o uso. Então, as duas formas seriam suportadas, porém caso a _query string_ esteja presente, ela será prioritária com relação ao _header_ `Accept`.

Talvez o melhor não seja usar `format` e sim algo mais parecido com HTTP: sugiro `content-type`. Exemplo: `/unidades-federativas/rj/?content-type=n3`.
