### ISSUE TITLE
Erro 500 no endpoint weekly, site incompleto

### ISSUE THREAD

**Issue by ricardo-comar** [turicas/brasil.io#517]
Ao abrir o site https://brasil.io/covid19 a chamada ao endpoint https://brasil.io/covid19/historical/weekly/ está retornando erro 500. 

Isso está impossibilitando de visualizar os gráficos restantes na tela de análises semanais.

**Comment by turicas** [comment]
@ricardo-comar, foi corrigido. Ainda estamos com atraso nos dados de óbitos registrados em cartório, mas os gráficos estão aparecendo corretamente. Obrigado!
