### ISSUE TITLE
Gostaria da lista atualizada

### ISSUE THREAD

**Issue by NMorale** [turicas/brasil.io#530]
Preciso ter as informações de covid atualizada todos os dias automaticamente

**Comment by NMorale** [comment]
Um link que eu possa incorporar no PowerBi

**Comment by turicas** [comment]
@NMorale, esse não é o canal para isso.
Leia esses posts em nosso blog:
- [Como acessar os dados do Brasil.IO](https://blog.brasil.io/2020/10/10/como-acessar-os-dados-do-brasil-io/)
- [Nossa API será obrigatoriamente autenticada](https://blog.brasil.io/2020/10/31/nossa-api-sera-obrigatoriamente-autenticada/)
