### ISSUE TITLE
Fix pg memory error

### ISSUE THREAD

**Issue by turicas** [turicas/brasil.io#57]
Internal Server Error: /dataset/documentos-brasil
It happens when we try to filter by some specific fields (like document type = CPF in documentos-Brasil dataset). 

```
OperationalError at /dataset/documentos-brasil could not resize shared memory segment “/PostgreSQL.125637135” to 50438144 bytes: No space left on device
```

**Comment by turicas** [comment]
https://www.postgresql.org/message-id/CAEepm%3D2wXSfmS601nUVCftJKRPF%3DPRX%2BDYZxMeT8M2WwLSanVQ%40mail.gmail.com

**Comment by flavioamieiro** [comment]
Rodar o container definindo o parâmetro [`--shm-size`](https://docs.docker.com/engine/reference/run/#runtime-constraints-on-resources) para um valor maior do que o padrão deve ajudar.

**Comment by turicas** [comment]
Já tinha feito isso e esqueci de fechar.
