### ISSUE TITLE
Criar arte de adesivos

### ISSUE THREAD

**Issue by turicas** [turicas/brasil.io#72]
Talvez fazer em formato hexagonal, como esses: http://hexb.in/

Possíveis gráficas:
- https://www.stickermule.com/
- https://www.diginate.com/
- https://www.agrafica.com.br/

Ideias/experimentações:

![adesivo-brasilio-1](https://user-images.githubusercontent.com/186126/40662618-441a3b50-632d-11e8-8589-d823b3c36b52.png)
![adesivo-brasilio-2](https://user-images.githubusercontent.com/186126/40662619-4438f5a4-632d-11e8-9d0c-7e5557d9fe65.png)
![adesivo-brasilio-3](https://user-images.githubusercontent.com/186126/40662620-4457795c-632d-11e8-85fe-229ecc1ac704.png)
![adesivo-brasilio-4](https://user-images.githubusercontent.com/186126/40662622-44872170-632d-11e8-9ca9-4784a8f31670.png)

**Comment by berinhard** [comment]
Achei o segundo mais maneiro, mas gostei do primeiro também :+1:

**Comment by letuche** [comment]
Fechamos nesta versão aqui. @turicas, subo os arquivos também no repositório? Aqui no meu local eu criei uma pasta "branding", o que acha?

![adesivo-hex-v3](https://user-images.githubusercontent.com/20052327/40685201-f00098e2-6369-11e8-8c0d-075bf368b40f.png)

**Comment by juhhcarmona** [comment]
Bem bacana os stickers! Pra fazer stickers tem a https://www.stickersdevs.com.br tbm :)

**Comment by juhhcarmona** [comment]
Bem bacana os stickers! Pra fazer stickers tem a https://www.stickersdevs.com.br tbm :)

**Comment by turicas** [comment]
@letuche, acho ótimo! Você cria um PR com isso, por favor? =)
@juhhcarmona, legal! Mandei email pra eles. ;)

**Comment by turicas** [comment]
Resposta da sticker devs:
```Boa tarde Álvaro!

Nós trabalhamos com vinil fosco de alta qualidade. Se preferir podemos fazer laminação fosca também.
Para produção preferimos o arquivo em vetor (pode ser SVG) para garantir uma qualidade melhor de impressão.

Segue:

Stickers Adesivos impressos em alta resolução em Vinil Premium

Sem laminação:

20 unidades -   R$ 2,19 cada
50 unidades - R$ 1,99 cada

Com laminação:

20 unidades -   R$ 2,99 cada
50 unidades - R$ 2,69 cada

Pagamento via Depósito Itaú
Produção em 5 a 7 dias úteis (sem prazo de frete incluído)

Frete a combinar.
Para quantidades pequenas sugerimos Carta Registrada R$ 10,00 com prazo de 3 a 5 dias úteis.
```

Achei caro. Das outras opções que vi sempre ficam em menos de 1 real cada adesivo.
