### ISSUE TITLE
Mostrar e importar todas as tabelas de um dataset

### ISSUE THREAD

**Issue by berinhard** [turicas/brasil.io#78]
Hoje o comando `import_data` importa sempre a primeira tabela (`default=True`) de um dataset. A ideia é introduzir um novo parâmetro para o comando especificando a tabela.

Portanto, para importar todos os dados do dataset `cursos-prouni`, executaríamos:

```
$ python manage.py import_data cursos-prouni cursos cursos.csv.xz
$ python manage.py import_data cursos-prouni campi campi.csv.xz
```

Tarefas:

- [x] Criar migração para renomear tabelas já existentes em produção
- [x] Alterar maneira como models de datasets são gerados para utilizar novo padrão de nomes
- [x] Mostrar tabelas na interface, podendo ver os dados de cada uma delas
- [x] Alterar comando `import_data` para suportar a inclusão de novas tabelas
- [x] Adicionar campo `last_updated` no `Table` e mostrá-lo na interface

**Comment by berinhard** [comment]
Deixando aqui os rascunhos que escrevi quando conversei com o @turicas sobre isso:

```
- viabilizar a importação de tabelas específicas de um dataset
    backward incompability está valendo
- pensar a migração de dados para renomear as tabelas já existentes
    hoje o nome tá só a app_dataset e teria que ser app_dataset_table
    usar a roubada do ProgrammingError para ver se a tabela existe
```

**Comment by berinhard** [comment]
From @turicas: 

Cara, tem como vc adicionar uma feature nessa issue dae? Isso vai impactar a interface também, dado que vai ter que ter agora um `/dataset/<slug>/<tabela>` (em `/dataset/<slug>` pode mostrar a tabela que tá como `default=True`, mas tem que ter as opções para as outras). É muito importante ter um dado "ultima atualizacao" em cada tabela. Vc consegue já criar esse campo? Daí ele seria preenchido no `import_data` e exibido na página do dataset/tabela.

**Comment by turicas** [comment]
Deixei a issue um pouco mais genérica e já estou trabalhando nela.
