### ISSUE TITLE
Como será a funcionalidade de busca/filtros?

### ISSUE THREAD

**Issue by turicas** [turicas/brasil.io#8]
Perguntas a serem respondidas:
- Quais parâmetros aceitar na _query string_ para filtrar dados? Filtros por determinados valores, ordernação etc.
- Quais parâmetros estarão presentes em recursos do tipo "coleção" e recursos do tipo "instância"?
- Teremos busca por texto completo? Faz sentido?

**Comment by miguelpeixe** [comment]
A query pode ser específica dentro de valores dentro do dado?

Por exemplo:
`/mortalidade_infantil/?com_vacinacao=true`
