### ISSUE TITLE
Criar páginas de erro 404 e 500 personalizadas

### ISSUE THREAD

**Issue by turicas** [turicas/brasil.io#93]
As de erro 500 podem conter algo assim: "ooops, aconteceu um problema com nosso servidor, mas fique tranquila que já fomos notificados e trabalharemos para corrijir."

Ambas poderiam ter: "caso você queira saber mais detalhes, entre em contato (link para página de contato)".

As páginas 404 não precisam ser personalizadas, podem ser genéricas. É só para a usuária do site não receber um erro seco, sem o visual do Brasil.IO.

**Comment by danilolutz** [comment]
Olá, eu tentaria uma mensagem menos presa ao gênero... algo como:
"ooops, aconteceu um problema com nosso servidor, não se preocupe que já fomos notificados e trabalharemos para corrigir" assim fica independente do gênero e bem genérica. Mas é apenas uma sugestão...

**Comment by jessicapaz** [comment]
Hey @turicas, quero trabalhar nessa issue, posso pegar?

**Comment by turicas** [comment]
Pode sim, @jessicapaz! Obrigado :)
